/** Common SQL keywords/snippets offered as fallback suggestions in any SQL-aware text field —
 * shown alongside (and ranked below) table/column matches. Kept to the surface actually used
 * across HANA/PostgreSQL DML plus basic DDL; not an exhaustive grammar. */
export const SQL_KEYWORDS: string[] = [
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "OR",
  "NOT",
  "IN",
  "LIKE",
  "BETWEEN",
  "IS NULL",
  "IS NOT NULL",
  "ORDER BY",
  "GROUP BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "AS",
  "DISTINCT",
  "JOIN",
  "INNER JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "FULL JOIN",
  "ON",
  "UNION",
  "UNION ALL",
  "EXISTS",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "ASC",
  "DESC",
  "INSERT INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE FROM",
  "CREATE TABLE",
  "ALTER TABLE",
  "DROP TABLE",
  "COUNT(*)",
  "SUM(",
  "AVG(",
  "MIN(",
  "MAX(",
  "NULL",
  "TRUE",
  "FALSE",
];

/** Narrower subset sensible inside a bare WHERE-clause fragment (the data grid's filter box, or
 * Audit Log's raw-SQL WHERE mode) — no SELECT/FROM/JOIN noise, since the table is already fixed. */
export const WHERE_CLAUSE_KEYWORDS: string[] = ["AND", "OR", "NOT", "IN", "LIKE", "BETWEEN", "IS NULL", "IS NOT NULL", "EXISTS", "NULL", "TRUE", "FALSE"];
